version: '2'

networks:
   DEV-HOMO:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: HOMO_nginx
        ports:
            - "1020:80"
            - "441:443"
        volumes:
            - ./webapps:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs:/var/log/nginx
            - ./nginx/ssl:/etc/nginx/ssl
        depends_on:
            - php
        restart: on-failure
        networks:
            - DEV-HOMO

    mariaDB:
        image: yobasystems/alpine-mariadb:latest
        container_name: HOMO_mariaDB
        volumes:
            - ./database:/var/lib/mysql:rw
        ports:
            - "1306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=devhomo*3fti
            - MYSQL_DATABASE=devhomo
            - MYSQL_USER=devhomo
            - MYSQL_PASSWORD=devhomo*
            - MYSQL_CHARSET=utf8mb4
            - MYSQL_COLLATION=utf8mb4_general_ci
        restart: on-failure
        networks:
            - DEV-HOMO

    php:
        image: php:7-fpm-alpine
        container_name: HOMO_php7
        volumes:
            - ./webapps:/usr/share/nginx/html
        ports:
            - "1900:9000"       
        restart: on-failure
        networks:
            - DEV-HOMO

    phpmyadmin:
        image: izone/arm:phpmyadmin
        container_name: HOMO_phpMyAdmin
        ports:
            - "1080:80"
        environment:        
            - PMA_ARBITRARY=1
            - PMA_HOST=mariaDB
        depends_on:
           - mariaDB
        restart: on-failure
        links:
            - mariaDB
        networks:
            - DEV-HOMO
